# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/beego" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/fiber" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/gin" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/revel" 
    schedule:
      interval: "weekly"